# Generated by Django 5.1.5 on 2025-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='auther',
            new_name='author',
        ),
    ]
